// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwtauthoption.proto

package jwtauthoption

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Scopes struct {
	And                  []string `protobuf:"bytes,1,rep,name=and,proto3" json:"and,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scopes) Reset()         { *m = Scopes{} }
func (m *Scopes) String() string { return proto.CompactTextString(m) }
func (*Scopes) ProtoMessage()    {}
func (*Scopes) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e351ae37afd4ae, []int{0}
}

func (m *Scopes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scopes.Unmarshal(m, b)
}
func (m *Scopes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scopes.Marshal(b, m, deterministic)
}
func (m *Scopes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scopes.Merge(m, src)
}
func (m *Scopes) XXX_Size() int {
	return xxx_messageInfo_Scopes.Size(m)
}
func (m *Scopes) XXX_DiscardUnknown() {
	xxx_messageInfo_Scopes.DiscardUnknown(m)
}

var xxx_messageInfo_Scopes proto.InternalMessageInfo

func (m *Scopes) GetAnd() []string {
	if m != nil {
		return m.And
	}
	return nil
}

var E_Scopes = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*Scopes)(nil),
	Field:         120645591,
	Name:          "jwtauth.scopes",
	Tag:           "bytes,120645591,rep,name=scopes",
	Filename:      "jwtauthoption.proto",
}

func init() {
	proto.RegisterType((*Scopes)(nil), "jwtauth.Scopes")
	proto.RegisterExtension(E_Scopes)
}

func init() { proto.RegisterFile("jwtauthoption.proto", fileDescriptor_70e351ae37afd4ae) }

var fileDescriptor_70e351ae37afd4ae = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x2a, 0x2f, 0x49,
	0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x87, 0x0a, 0x4a, 0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x85, 0x93, 0x4a,
	0xd3, 0xf4, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b, 0x20, 0x4a, 0x95, 0xa4,
	0xb8, 0xd8, 0x82, 0x93, 0xf3, 0x0b, 0x52, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0x13, 0xf3, 0x52, 0x24,
	0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x2b, 0x2f, 0x2e, 0xb6, 0x62, 0x88, 0x9c, 0x9c,
	0x1e, 0xc4, 0x20, 0x3d, 0x98, 0x41, 0x7a, 0xbe, 0xa9, 0x25, 0x19, 0xf9, 0x29, 0xfe, 0x60, 0x5b,
	0x8b, 0x25, 0xae, 0x9f, 0x3f, 0x6c, 0xa9, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xaf, 0x07, 0xb5, 0x5a,
	0x0f, 0x62, 0x6a, 0x10, 0xd4, 0x04, 0x27, 0xfe, 0x28, 0x5e, 0x14, 0x97, 0x26, 0xb1, 0x81, 0x8d,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xbb, 0xef, 0xfb, 0xc1, 0x00, 0x00, 0x00,
}
